### ISSUE TITLE
Replace non-free RAM code

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#1]
The wiki states, that the STM8_serial_flasher is under ASL, "exception is some RAM code, which is required for flash programming. This code was copied from the free Flash Loader Demonstrator by STM. All rights to this RAM code remain with STM." The non-free code should be replaced by free code to make STM8_serial_flasher fully free.

Philipp

**Comment by spth** [comment]
Another option would be to ask ST to free the current code.

Philipp

**Comment by gicking** [comment]
done just now. Answer pending...

**Comment by gicking** [comment]
obsolete after confirmation by ST support that now ultimate-liberty-v2 license applies (http://www.st.com/software_license_agreement_liberty_v2), which allows re-distribution
