### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#10]
IMO, the current name of this program is a bit unfortunate. It is nearly the same name as the earlier Chrome app "stm-serial-flasher". Also "serial" doesn't mean that much, as pretty much any method to access the flash of the STM8 uses some serial connection.
An important aspect of this program is that it uses the bootloader. The first name that comes to my mind would be "stm8bootflash", but there may be better names.

Philipp

**Comment by gicking** [comment]
yep, agreed. I also already got confused in the past with all the similar names. As an excuse I can only say that I started this tool for my own personal use, so it didn't really matter.

"stm8bootflash" sounds good but let me sleep over it. Maybe somebody else reads this and has an idea...!?

**Comment by gicking** [comment]
ok, slept it over and did some internet browsing --> for the Atmel uC family the PC flash tool is called avrdude, so how about stm8dude or stmdude? Remarks:
- avrdude supports BSL and ISP operation, so essentially it combines [stm8flash](https://github.com/vdudouyt/stm8flash) and [STM8_serial_flasher](https://github.com/gicking/STM8_serial_flasher). But who's perfect... :wink:
- I'll ask Georg O. how big the difference between STM8 and STM32 boot loading is. If it's realistic, I'll implement STM32 as well. In that case we should go for stmdude. If not IMO stm8dude is better suited

**Comment by spth** [comment]
stmdude seems ok. Personally, I'd probably prefer stmgal (since it sounds similar to stcgal - a tool for the mcs51 clones by STC, another 8-bit architecture supported by SDCC).

Philipp

**Comment by gicking** [comment]
renamed to stm8gal and moved to https://github.com/gicking/stm8gal
