### ISSUE TITLE
CAN support

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#2]
Support for using the bootloader via CAN would be useful.
However support for CAN drivers is not available universally in operating systems, so maybe this would be implemented for Linux only? It seems the current dominant API is SocketCAN by Volkswagen. But I noticed mention of older, character-based APIs, too.

Philipp

**Comment by gicking** [comment]
maybe I was a bit too quick proposing CAN support. Basically I was only thinking about the STM8 side of the communication, not the PC side. Any idea which HW and SW-API would be sensible? Surely not bitbang mode, no it has to be some kind of embedded adapter like CANoe or Arduino with CAN shield...? Surely possible but I guess it's a long shot! Therefore I propose to focus on the other points, first...?

**Comment by spth** [comment]
On Linux, SocketCAN is the standard API, which works with drivers for the hardware. According to http://fabiobaltieri.com/2013/07/23/hacking-into-a-vehicle-can-bus-toyothack-and-socketcan/ there were already 5 USB-to-CAN interfaces supported by Linux drivers backin 2013.
Other OSes don't seem to have support yet, but I guess if they ever do they will follow Linux.

Philipp

**Comment by gicking** [comment]
moved to [stm8gal repo issues](https://github.com/gicking/stm8gal/issues/2)
