### ISSUE TITLE
SPI support

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#3]
Support for using the bootloader via SPI would be useful.
However, few operating systems seem to expose SPI to userspace. Linux does. I see patches for it on the FreeBSD mailing list, so maybe they'll add it soon.

Philipp

**Comment by gicking** [comment]
actually I was thinking about Raspberry Pi and Wiring. This is similar to the optional HW reset of the STM8 via GPIO prior to bootloader initialization.

Do you have any documentation how to access the SPI via SW under "normal" Linux? And how does the HW look like? Via bitbang mode of e.g. a FTDI chip?

I guess SPI support would be MUCH easier than CAN (see #2). Anyhow let's first get UART/LINUART support right for as many devices as possible...

**Comment by spth** [comment]
https://www.kernel.org/doc/Documentation/spi/spidev

Philipp

**Comment by gicking** [comment]
moved to [stm8gal repo issues](https://github.com/gicking/stm8gal/issues/1)

**Comment by gicking** [comment]
in stm8gal (new name, same tool, see https://github.com/gicking/stm8gal), added support for SPI via "Arduino USB-SPI bridge" (see https://github.com/gicking/Arduino_SPI_bridge). This allows SPI upload from PCs without spidev support and/or compatible hardware. Have fun!
