### ISSUE TITLE
Binary files

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#5]
Currently, Intel .hex and Motorola .s19 files are supported. I suggest to add support for binary files, too.

Philipp

**Comment by spth** [comment]
I'm working on this in a branch.

Philipp

**Comment by gicking** [comment]
:-)  that's good to hear!

One stupid question though: could you please support me in merging your changes to the main branch after you're done? So far I used Github mainly as a distribution tool, not as a versioning system with branches etc. Sorry to bother you with this!

**Comment by spth** [comment]
Tested an ready to merge. Unfortunately, I'm new to git and GitHub, mostly work with svn and Sourceforge.

Philipp

**Comment by gicking** [comment]
tja dann versuche ich mich mal daran…

**Comment by gicking** [comment]
es gibt da einen Button „Merge Pull Request“, schein also kein Hexenwerk :-)

Aber bevor ich den drücke hätte ich noch ein paar Fragen zu Deinen Änderungen. Hast Du ein paar Minuten und bist Du unter Tel. 069-79828114 erreichbar?

Georg

**Comment by spth** [comment]
> Hast Du ein paar Minuten und bist Du unter Tel. 069-79828114 erreichbar?

Nicht unter der Nummer, aber unter einer, die ich Dir nun per Email geschreiben habe.

Philipp

**Comment by spth** [comment]
Implemented by merge.

Philipp
