### ISSUE TITLE
Support STM8L / STM8AL, only use RAM routines as necessary

### ISSUE THREAD

**Issue by spth** [gicking/STM8_serial_flasher#9]
For the STM8L/STM8AL, RAM routines are already put in place by the bootloader, and need not be supplied by the host computer.

Philipp

**Comment by spth** [comment]
It seems, the STM8L/STM8AL have eeprom at 0x1000, while the STM8S/STM8AF have it at 0x4000. Some, but not all STM8S/STM8AF enough RAM, so that 0x1000 is in RAM. Maybe this can be used to decide if routines need to be supplied?

Philipp

**Comment by gicking** [comment]
I agree that in order to be useful the tool has to support all STM8 devices with BSL support. However, my main issue here is that I currently only have two STM8 to work with (STM8S105 and STM8AF52AA). So it'll be kind of tricky to assert the most reliable way for determining the respective device

Do you know where I can find an overview of all STM8 parts with boot loader support? And on a similar note: do you know which (cheap) boards I could order to broaden my "HW basis"? Thanks in advance!

**Comment by spth** [comment]
> Do you know where I can find an overview of all STM8 parts with boot loader support?

"STM8 bootloader", DocID14798 Rev 9, Table 1 on page 6 has the information for most STM8 devices (STLUX, STM8SPLNB1 and STNRG are missing).

Philipp

**Comment by spth** [comment]
> And on a similar note: do you know which (cheap) boards I could order to broaden my "HW basis"?

There are two categories of cheap boards: One one hand the Discovery ones by ST, which include an ST-Link or ST-Link/v2. On the other hand the very cheap no-name minimal boards, for which an extra ST-Link is required (but again, there are very cheap ST-Link/v2 clones). The latter are available on in various places, some directly from China, some from resellers elsewhere (at a higher price, but shipping faster). But the very cheap boards seem to all have a low-end STM8S. Most of the very cheap boards feature STM8 without bootloader, but there is one exception: Boards with the STM8S105.

My page on STM8 tutorials at http://www.colecovision.eu/stm8/ provides an overview on the boards I wrote tutorials for.

Philipp

**Comment by gicking** [comment]
hi,

as proposed by Philipp, reading from 0x4000 fails for STM8L (reserved) but is ok for STM8A/S (EEPROM). So I can use this to identify the (rough) family, and skip RAM upload for STM8L. Not the perfect solution, but seemingly it works. I'll upload the code after some more testing :-)

**Comment by spth** [comment]
I noticed you used the term "STM8AS" vs "STM8L" in the code. This seems a bit misleading, since:
AFAIK all STM8 are either STM8S or STM8L-based and behave that way wrt. the bootloader. In particular: STM8AF, STLUX, STNRG, STM8SPLNB are the same as STM8S. STM8AL, STM8T are the same as STM8L.

Philipp

**Comment by spth** [comment]
I had a quick look at the code, but wasn't sure if the patch for STM8L low-density devices is implemented. For these devices (but not other STM8L devices), the single byte 0xb2 needs to be written to 0x1ea.

Philipp

**Comment by gicking** [comment]
hi Philipp,

you are right, STM8AS was supposed to be mean STM8A and STM8S, which actually are identical, except for test depth. So I figure you propose that I only use STM8S throughout the code and Wiki...? I have no issue with that, so consider it done...

Regarding STM8L I wasn't even aware that it's identical to STM8T. Thanks for pointing it out :-)

Regards, Georg

**Comment by gicking** [comment]
hello again,

regarding the different devices I wasn't quite sure how to handle them. Specifically I took a while to figure that STM8L doesn't require RAM upload prior to flashing - but that the 8kB STM8L (aka "low density") does - at least there exists a S19 file for it which contains data...

In any case, in main.c line 420 I tried to handle this. Is this what you mean? If not, please let me know. Thanks in advance!

Georg

**Comment by gicking** [comment]
hello again,

just checked your comment for the STM8L low density, and the file "E_W_ROUTINEs_8K_verL_1.0.s19" by STM and hence the RAM code I upload in case of STM8L low-density (see main.c, line 420) does indeed contain only 1 byte, namely 0xb2 at 0x1ea. Unfortunately (again) I can't test it due to a missing board. But theoretically it should work. What do you think?

Georg

**Comment by gicking** [comment]
removed all STM8AS with STM8S as proposed.

When/if you also agree to the above comment on STM8L low-density I will close this issue...?

**Comment by gicking** [comment]
issue closed, see above
